apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.16.0 (HEAD)
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    io.kompose.service: www-fintlabs
  name: www-fintlabs
spec:
  ports:
    - name: "80"
      port: 80
  type: LoadBalancer
  selector:
    io.kompose.service: www-fintlabs
status:
  loadBalancer: {}
