apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.16.0 (HEAD)
  labels:
    io.kompose.service: www-fintlabs
  name: www-fintlabs
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      io.kompose.service: www-fintlabs
  template:
    metadata:
      labels:
        io.kompose.service: www-fintlabs
    spec:
      restartPolicy: Always
      containers:
        - name: content
          image: fintlabs.azurecr.io/www-fintlabs-content-server:build.1
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "64Mi"
              cpu: "500m"
        - name: frontend
          image: fintlabs.azurecr.io/www-fintlabs-frontend:build.3
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "64Mi"
              cpu: "500m"
